config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  resources :users

  root 'zilog#index'
  get  '/',              to: 'zilog#index'
  get  '/disasm',        to: 'zilog#disasm'
  post '/disasm',        to: 'zilog#disasm'
  get  '/emulator',      to: 'zilog#emulator'
  post '/compile',       to: 'zilog#compile'
  get  'download_tap',   to: 'zilog#download_tap'
  get  'download_sna',   to: 'zilog#download_sna'
  get  'download_hob',   to: 'zilog#download_hob'
  get  'download_cod',   to: 'zilog#download_cod'
  get  '/converter_hex', to: 'zilog#converter_hex'
  post '/converter_hex', to: 'zilog#converter_hex'
  get  '/converter_dec', to: 'zilog#converter_dec'
  post '/converter_dec', to: 'zilog#converter_dec'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
# frozen_string_literal: true

class Authorization < ApplicationRecord
  belongs_to :user
end

app/models/converter.rb
# frozen_string_literal: true

class Converter
  attr_reader :file_size

  def initialize(params)
    @size      = params[:size]&.to_i               || 1
    @prefix    = params[:prefix]                   || '#'
    @splitter  = params[:splitter]&.to_i           || 8
    @separator = params[:separator]&.sub('_', ' ') || ', '
    @define    = params[:define]&.sub('none', '')  || ''
    @array     = []
    @file      = File.open(params[:file])
    @file_size = @file.size
  end

  def hex
    @file.each_byte { |byte| @array << byte.to_s(16).rjust(2, '0') }
    @array = @array.each_slice(@size).map(&:join).map { |str| @prefix + str }
    join_to_str
  end

  def dec
    @file.each_byte { |byte| @array << byte.to_s }
    join_to_str
  end

  private

  def join_to_str
    @array.each_slice(@splitter).to_a.map do |str|
      z = str.join(@separator)
      @define.present? ? "\t#{@define} #{z}" : z
    end.join("\n")
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :trackable, :recoverable, :rememberable,
         :validatable, :omniauthable, omniauth_providers: [:firebase, :telegram, :yandex]
  has_many :authorizations, dependent: :destroy

  def self.find_for_oauth(auth)
    authorization = Authorization.where(provider: auth[:provider], uid: auth[:uid]).first
    return authorization.user if authorization

    user = User.where(email: auth[:email], provider: auth[:provider]).first
    user ||= User.create!(auth)
    user.create_authorization(auth)
    user
  end

  def create_authorization(auth)
    authorizations.create(provider: auth[:provider], uid: auth[:uid])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/callbacks_controller.rb
# frozen_string_literal: true

class CallbacksController < Devise::OmniauthCallbacksController
  def yandex
    upsert_user('YANDEX')
  end

  def telegram
    upsert_user('TELEGRAM')
  end

  def firebase
    upsert_user('FIREBASE')
  end

  private

  def upsert_user(provider)
    @user = User.find_for_oauth(auth(request.env['omniauth.auth'] || params))
    return unless @user.persisted?

    sign_in_and_redirect @user, event: :authentication
    set_flash_message(:notice, :success, kind: provider) if is_navigational_format?
  end

  def auth(params) # rubocop:disable Metrics/MethodLength
    email    = params.dig(:user, :email).present? ? params.dig(:user, :email) : params.dig(:info, :email)
    uid      = params[:uid]      || params.dig(:user, :uid)
    provider = params[:provider] || params.dig(:user, :provider)
    password = Devise.friendly_token[0, 20]
    {
        uid:      uid,
        provider: provider,
        email:    email || "#{params.dig(:user, :phone) || uid}@#{provider}",
        token:    params.dig(:credentials, :token)      || params[:token],
        name:     params.dig(:extra, :raw_info, :login) || params.dig(:user, :name),
        phone:    params.dig(:user, :phone),
        password: password,
        password_confirmation: password
    }
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    head(:ok)
  end

  def show; end
end

app/controllers/zilog_controller.rb
# frozen_string_literal: true

class ZilogController < ApplicationController
  protect_from_forgery with: :null_session

  PREFIX    = ['', '#', '$', '0x'].freeze
  SEPARATOR = ['_', ',', ',_'].freeze
  DEFINE    = ['none', 'db', 'defb', 'dw', 'defw'].freeze
  BASIC     = ['none', 'DATA', 'DB', 'DEFB'].freeze

  before_action :check_file
  before_action :converter, only: [:converter_hex, :converter_dec]

  def index; end

  def disasm
    @org = 32_768
    return if @error

    file = params[:demo] == 'true' ? demo : params[:file]
    service = Z80Disassembler::Disassembler.new(file, params[:org])
    @result    = service.start
    @file_size = service.file_size
    @org       = service.org
    render layout: false
  end

  def compile
    file = Tempfile.new(file_name)
    file.write(params[:file])
    file.write(Z80Disassembler::Disassembler.compile_text(file_name))
    file.close
    @compiled = system "sjasmplus --nologo #{file.path} 2> #{file_name}.log"
    @logs = File.read("#{file_name}.log").split("\n")
    render layout: false
  end

  def emulator; end

  def converter_hex
    return if @error

    @result = @converter.hex
    render layout: false
  end

  def converter_dec
    @values = (1..16).to_a + (5..10).map { |x| 2**x } + [6912]
    return if @error

    @result = @converter.dec
    render layout: false
  end

  def download_tap = send_file("#{file_name}.tap", filename: 'disasm.tap')
  def download_sna = send_file("#{file_name}.sna", filename: 'disasm.sna')
  def download_hob = send_file("#{file_name}.$C",  filename: 'disasm.$C' ) # rubocop:disable Layout/SpaceInsideParens
  def download_cod = send_file("#{file_name}.bin", filename: 'disasm.bin')

  private

  def demo
    ActionDispatch::Http::UploadedFile.new(tempfile: File.open('snow16.$C'), filename: 'snow16.$C')
  end

  def file_name
    return @file_name if @file_name

    dir = current_user ? "tmp/users/user_#{current_user.id.to_s(16).rjust(4, '0')}" : 'tmp'
    FileUtils.mkdir_p(dir)
    @file_name = "#{dir}/disasm"
  end

  def converter
    return if @error

    @converter = Converter.new(params)
    @file_size = @converter.file_size
  end

  def check_file
    @result = if params[:file].nil? || params[:file] == 'undefined'
                'File not found'
              elsif params[:file].size > (1024 * 1024)
                'File size > 1mb'
              end
    @error = @result.present? && params['demo'] != 'true'
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(level)
    {
      notice:  'alert alert-info',
      success: 'alert alert-success',
      error:   'alert alert-error',
      alert:   'alert alert-error'
    }[level]
  end
end

app/views/layouts/application.slim
doctype html
html
  head
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true
    = favicon_link_tag asset_path('favicon-zxn.png')

    title ZX Spectrum & Z80 online tools | ZXN.RU
    link href="/public/favicon.ico" rel=('shortcut icon') type="image/x-icon"
    link href="https://zxn.ru"     rel="canonical"
    meta name="description"        content="Collection of useful online tools for retro-coding on 8bit computers"
    meta name="twitter:card"       content="summary_large_image"
    meta property="og:url"         content="https://zxn.ru/"
    meta property="og:site_name"   content="ZX Spectrum & Z80 online tools"
    meta property="og:type"        content="website"
    meta property="og:title"       content="ZX Spectrum & Z80 online development tools"
    meta property="og:locale"      content="en_EN"
    meta property="og:description" content="Z80 disassembly, BIN to HEX, online ZX Spectrum emulator and other magic..."
    meta property="og:image"       content="#{asset_path('og-image-zxn.png')}"

  = yield

  footer.footer
    .content.has-text-centered
      div
        a.strong href='https://zxn.ru' zxn.ru
        | &nbsp
        | by
        | &nbsp
        a.strong href='https://rmda.su' RMDA
      div
        a href='https://t.me/dvitvitskiy' Telegram
        | &nbsp; / &nbsp;
        a href="mailto:dvitvitskiy.pro@gmail.com" Email
      div
        | The source code is licensed
        a href="http://opensource.org/licenses/mit-license.php"  MIT
        | &nbsp
        | Copyright &copy;
        = " 2019-#{Time.now.year}"

javascript:
    if ("#{Rails.env}" === 'production') {
        (function (m, e, t, r, i, k, a) {
            m[i] = m[i] || function () { (m[i].a = m[i].a || []).push(arguments) };
            m[i].l = 1 * new Date();
            k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
        })
        (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
        ym(81052243, "init", {clickmap: true, trackLinks: true, accurateTrackBounce: true, webvisor: true});
    }

app/views/zilog/_compile.slim
div
  p
    - @logs.each do |log|
      div = log
  - if @compiled
    ul
      li= link_to 'download .tap',         download_tap_url
      li= link_to 'download .sna',         download_sna_url
      li= link_to 'download .$C (Hobeta)', download_hob_url
      li= link_to 'download .bin (code)',  download_cod_url

app/views/zilog/_converter.slim
.columns.is-centered
  .column.is-12
    .buttons.has-addons
      = link_to '', '#', class: 'button is-large is-danger'
      = link_to '', '#', class: 'button is-large is-warning'
      = link_to 'Copy to clipboard', '#', class: 'button is-large is-info', onclick: 'copy_to_clipboard()'
      = link_to 'Download', '#', class: 'button is-large is-success', onclick: 'download_txt()'
    br
    textarea.textarea#textarea rows="25" = @result

app/views/zilog/_disasm.slim
.columns.is-centered
  .column.is-12
    .buttons.has-addons
      / - if params[:action] == 'disasm'
      = link_to 'Compile', '#', class: 'button is-large is-danger is-rounded', onclick: 'compile_txt()'
      / = link_to 'Run .TAP', '#', class: 'button is-primary', id: :fff
      = link_to 'Demo', disasm_path(demo: true), class: 'button is-large is-warning is-rounded', remote: true
      = link_to 'Download', '#', class: 'button is-large is-success is-rounded', onclick: 'download_txt()'
      = link_to 'Copy to clipboard', '#', class: 'button is-large is-info is-rounded', onclick: 'copy_to_clipboard()'
    br
    textarea.textarea#textarea rows="38" = @result

app/views/zilog/compile.js.erb
$('#log').html("<%= j render partial: 'compile' %>");

app/views/zilog/converter_dec.js.erb
$('.file').html("<%= j render partial: 'converter' %>");
$('#file_size').html(<%= @file_size %> + ' bytes');

app/views/zilog/converter_dec.slim
section.hero.is-lower-alpha
  .hero-body
    .container.has-text-white
      h1.title.is-1
        = link_to 'ZXN.RU', root_path
      .columns.is-centered
        .column.is-3
          = label_tag :splitter, 'Row size:'
          span &nbsp
          span#row_size
          .d-flex
            form.range-field.w-100
              input.form-range max="#{@values.size - 1}" min="0" type="range" id="splitter" value="4"
          .text-center
            sup = "1..16, #{@values[16..].join(", ")}"
        .column.is-3
          = 'Define:'
          .control
            - ZilogController::BASIC.each_with_index do |define, index|
              p
                label.radio
                  label.radio
                    = radio_button_tag(:define, define, define == 'DATA', class: 'form-check-input')
                    | &nbsp
                    = define
        .column.is-3
          = 'Separator:'
          .control
            - ZilogController::SEPARATOR[1..].each_with_index do |separator, index|
              p
                label.radio
                  = radio_button_tag(:separator, separator, separator == ',', class: 'form-check-input')
                  | &nbsp
                  = separator
        .column.is-3
          = label_tag :file, 'File:'
          span &nbsp
          span#file_size
          p = file_field_tag :file, class: 'form-control'

section#parallax-computers.hero
  .hero-body
    .container
      .file
        = render partial: 'converter'

javascript:
    var input = $('#splitter');
    function reload() {
        let formData = new FormData();
        formData.append('file', $('#file')[0].files[0]);
        formData.append('splitter', values[input.val()]);
        formData.append('define', $('input[name=define]:checked').val() || '');
        formData.append('separator', $('input[name=separator]:checked').val() || ', ');
        $.ajax({
            url: "#{converter_dec_path}",
            type: 'POST',
            data: formData,
            async: false,
            cache: false,
            contentType: false,
            enctype: 'multipart/form-data',
            processData: false
        })
    }

    var values = #{@values};
    $('#row_size').html(values[input.val()])
    input.change(() => $('#row_size').html( values[input.val()] ));
    $('select').change( () => reload() );
    $('input' ).change( () => reload() );

    function copy_to_clipboard() {
        $("#textarea").select();
        document.execCommand("copy");
    }

    function download_txt(str) {
        var blob = new Blob([$("#textarea").val()], {type: "text/plain;charset=utf-8"});
        saveAs(blob, 'file_' + Date.now() + ".asm");
    }

app/views/zilog/converter_hex.js.erb
$('.file').html("<%= j render partial: 'converter' %>");
$('#file_size').html(<%= @file_size %> + ' bytes');

app/views/zilog/converter_hex.slim
section.hero.is-lower-alpha
  .hero-body
    .container.has-text-white
      h1.title.is-1
        = link_to 'ZXN.RU', root_path
      .columns.is-centered
        .column.is-4
          = label_tag :size, "Bytes:"
          span &nbsp
          span#byte_size
          .d-flex
            span 1
            form.range-field.w-100
              input.form-range max="8" min="1" type="range" id="size" value="1"
            span 8
        .column.is-4
          = 'Separator:'
          div
            - ZilogController::SEPARATOR.each_with_index do |separator, index|
              .form-check.form-check-inline
                = radio_button_tag(:separator, separator, separator == ',', class: 'form-check-input')
                label.form-check-label for="separator_#{index}" = separator
        .column.is-4
          = label_tag :file, 'File:'
          span &nbsp
          span#file_size
          p = file_field_tag :file, class: 'form-control'
      .columns.is-centered
        .column.is-4
          = label_tag :splitter, 'Row size:'
          span &nbsp
          span#row_size
          p
            .d-flex
              span 1
              form.range-field.w-100
                input.form-range max="64" min="1" type="range" id="splitter" value="16"
              span 64
        .column.is-4
          = 'Define:'
          p
            - ZilogController::DEFINE.each_with_index do |define, index|
              .form-check.form-check-inline
                = radio_button_tag(:define, define, define == 'defb', class: 'form-check-input')
                label.form-check-label for="define_#{index}" = define
        .column.is-4
          = 'Prefix:'
          p
            - ZilogController::PREFIX.each_with_index do |prefix, index|
              .form-check.form-check-inline
                = radio_button_tag(:prefix, prefix, prefix == '#', class: 'form-check-input')
                label.form-check-label for="prefix_#{index}" = prefix

section#parallax-computers.hero
  .hero-body
    .container
      .file
        = render partial: 'converter'

javascript:
    function reload() {
        let formData = new FormData();
        formData.append('file', $('#file')[0].files[0]);
        formData.append('size', $('#size').val());
        formData.append('splitter', $('#splitter').val());
        formData.append('define', $('input[name=define]:checked').val() || '');
        formData.append('prefix', $('input[name=prefix]:checked').val() || '');
        formData.append('separator', $('input[name=separator]:checked').val() || ', ');
        $.ajax({
            url: "#{converter_hex_path}",
            type: 'POST',
            data: formData,
            async: false,
            cache: false,
            contentType: false,
            enctype: 'multipart/form-data',
            processData: false
        })
    }

    $('#byte_size').html($('#size').val())
    $('#row_size').html($('#splitter').val())

    $('#size').change( () => $('#byte_size').html($('#size').val()) );
    $('#splitter').change( () => $('#row_size').html($('#splitter').val()) );
    $('select').change( () => reload() );
    $('input' ).change( () => reload() );

    function copy_to_clipboard() {
        $("#textarea").select();
        document.execCommand("copy");
    }

    function download_txt(str) {
        var blob = new Blob([$("#textarea").val()], {type: "text/plain;charset=utf-8"});
        saveAs(blob, 'file_' + Date.now() + ".asm");
    }

app/views/zilog/disasm.js.erb
$('.file').html("<%= j render partial: 'disasm' %>");
$('#org').val(<%= @org %>);
$('#file_size').html(<%= @file_size %> + ' bytes');
$('#log').empty();


ace.edit("textarea", {
    mode: "./assembly_z80",
    theme: "ace-builds/src-noconflict/monokai",
    maxLines: 50,
    minLines: 20,
    fontSize: 12,
    autoScrollEditorIntoView: true,
    copyWithEmptySelection: true
});

app/views/zilog/disasm.slim
section.hero.is-lower-alpha
  .hero-body
    .container.has-text-white
      h1.title.is-1
        = link_to 'ZXN.RU', root_path
      .columns.is-centered
        .column.is-4
          p
            div = label_tag :org, 'ORG:'
            = number_field_tag :org, @org, min: 0, max: 65535, class: 'form-control'
          p
            .columns.is-centered
              - (1..4).each do |i|
                .column.is-3
                  = link_to '#', id: "inc_s#{i}", onclick: ("change('s#{i}', '>'); return false;") do
                    i.fas.fa-caret-up
            .columns.is-centered
              - (1..4).each do |i|
                .column.is-3
                  = select_tag "s#{i}", options_for_select((0..9).to_a + ('A'..'F').to_a, i==1 ? 8 : 0), id: "s#{i}", include_blank: false
            .columns.is-centered
              - (1..4).each do |i|
                .column.is-3
                  = link_to '#', id: "dec_s#{i}", onclick: ("change('s#{i}', '<'); return false;") do
                    i.fas.fa-caret-down
            = text_field_tag :org_hex, "##{@org.to_s(16)}", class: 'form-control', placeholder: '#'
        .column.is-4
          p
            = label_tag :file, 'File:'
            span &nbsp
            span#file_size
            = file_field_tag :file, class: 'form-control'
        .column.is-4
          p
            #log

section#parallax-computers.hero
  .hero-body
    .container
      .file
        = render partial: 'disasm'

javascript:

    function change(i, x) {
        var ddl = document.getElementById(i);
        if (x === '<' && ddl.selectedIndex === 0) {
            ddl.selectedIndex = 15
        } else if (x === '>' && ddl.selectedIndex === 15) {
            ddl.selectedIndex = 0
        } else {
            ddl.selectedIndex = x === '>' ? ddl.selectedIndex + 1 : ddl.selectedIndex - 1
        }
    }

    function reload() {
        let formData = new FormData();
        formData.append('file', $('#file')[0].files[0]);
        formData.append('org',  $('#org').val());
        if ($('#file')[0].files[0]) {
            $.ajax({
                url: "#{disasm_path}",
                type: 'POST',
                data: formData,
                async: false,
                cache: false,
                contentType: false,
                enctype: 'multipart/form-data',
                processData: false
            });
        }
    }

    $('select').change(() => change_hex());
    $('#inc_s1').click(() => change_hex());
    $('#dec_s1').click(() => change_hex());
    $('#inc_s2').click(() => change_hex());
    $('#dec_s2').click(() => change_hex());
    $('#inc_s3').click(() => change_hex());
    $('#dec_s3').click(() => change_hex());
    $('#inc_s4').click(() => change_hex());
    $('#dec_s4').click(() => change_hex());

    function change_hex() {
        let z1 = parseInt('0x' + $('#s1').val(), 16)
        let z2 = parseInt('0x' + $('#s2').val(), 16)
        let z3 = parseInt('0x' + $('#s3').val(), 16)
        let z4 = parseInt('0x' + $('#s4').val(), 16)
        let zz = z1 * 4096 + z2 * 256 + z3 * 16 + z4
        $('#org').val(zz)
        $('#org_hex').val('#' + $('#s1').val() + $('#s2').val() + $('#s3').val() + $('#s4').val())
        reload()
    }

    $('input[id="org_hex"]').change(() => {
        let hex = $('#org_hex').val().split('#')[1];
        $('#org').val(parseInt('0x' + hex, 16))
        reload()
    });
    $('input[id="org"]').change(() => {
        let num = parseInt($('#org').val(),10).toString(16)
        $('#org_hex').val('#' + num)
        $("#s1")[0].selectedIndex = num[0]
        $("#s2")[0].selectedIndex = parseInt('0x' + num[1], 16)
        $("#s3")[0].selectedIndex = parseInt('0x' + num[2], 16)
        $("#s4")[0].selectedIndex = parseInt('0x' + num[3], 16)
        reload()
    });

    $('#file').change(() => reload());

    function copy_to_clipboard() {
        let textarea = $('#textarea');
        textarea.val(editor.getValue());
        textarea.select();
        document.execCommand("copy");
    }

    function download_txt() {
        var blob = new Blob([editor.getValue()], {type: "text/plain;charset=utf-8"});
        saveAs(blob, 'file_' + Date.now() + ".asm");
    }

    function compile_txt() {
        let formData = new FormData();
        formData.append('file', editor.getValue());
        $.ajax({
            url: "#{compile_path}",
            type: 'POST',
            data: formData,
            async: false,
            cache: false,
            contentType: false,
            enctype: 'multipart/form-data',
            processData: false,
            success: (file) => {
                // debugger
                // const bytes = new Uint8Array(file.length);
                // let z = bytes.map((byte, i) => file.charCodeAt(i));
                // z.length
                // var blob = new Blob([file], {type: "multipart/form-data"});
                // saveAs(blob, 'disasm_' + Date.now() + ".tap");
            }
        });
    }

app/views/zilog/emulator.slim
section.hero.is-lower-alpha
  .hero-body
    .container.has-text-white
      h1.title.is-1
        = link_to 'ZXN.RU', root_path
      .columns.is-centered
        .column.is-4
          p
            = label_tag :files_selector, 'ФАЙЛ:'
            = file_field_tag :files_selector, accept: '.zip,.trd,.scl,.tap,.tzx,.z80,.rom', class: 'form-control'
        .column.is-9
          .btn-group-sm
            = link_to 'Reset ZX Spectrum', '#', class: 'btn btn-xs btn-outline-primary', id: :gogogo

section#parallax-computers.hero
  .hero-body
    .container
      #jsspeccy
    .container
      #game.right-contains
        div style=('overflow-x: hidden;')
          #playground style=('width:2540px;position:relative;overflow-x: hidden; overflow-y: hidden;left:0px;')
            div style='width:1000px;float:left;'
              #information
                .play_button
                  | .
            div style='width:20px;float:left;'  &nbsp;
            .appdat_inline_block style='width:500px;float:left;'
              div style='width:864px;float:left;'
                #fscontainer
                  #applet_place.shadow style=('width: 864px; height: 700px; position: relative; margin: auto; float: none;')

app/views/zilog/index.slim
section.hero.is-lower-alpha
  .hero-body
    .container
      h1.title.is-1
        = link_to 'ZXN.RU', root_path
      h2.subtitle
        | Get the retro-coding started in your browser right now!&nbsp
      h2.subtitle
        | This is a collection of useful online tools for Sinclair ZX Spectrum and Z80 assembly development.
      h2.subtitle
        - if current_user
          span
            .nav-link = current_user.email.present? ? current_user.email : current_user.phone
          span &nbsp
          span = link_to 'Sign Out', destroy_user_session_path, class: 'nav-link', method: :delete
        - else
          span = link_to 'Sign In', new_user_session_path

section#parallax-computers.hero
  .hero-body
    .container
      .columns.is-centered.is-multiline
        .column.is-4
          .card
            header.card-header
              p.card-header-title
                | File to HEX / DEC
            .card-content
              .content
                p Converts a binary file (server-side, your data is sent to server) to hex/decimal code. Input size is limited to 1 MB to meet our resources consumption. Please refer to offline tools to process larger files. Output result can be saved as text file or copied to clipboard in one click.
            footer.card-footer
              = link_to 'HEX', converter_hex_path, class: 'card-footer-item'
              = link_to 'DEC', converter_dec_path, class: 'card-footer-item'
        .column.is-4
          .card
            header.card-header
              p.card-header-title
                | Z80 Disassembler/Compiler
            .card-content
              .content
                | Simple server-side disassembler for any binary file into Zilog Z80 assembler instructions set. You can upload data and define ORG/START addresses. For Hobeta files input ORG address is autodetected. Output is formatted with SjASMPlus syntaxes and is ready to be compiled out of the box.
            footer.card-footer
              = link_to 'Disassembler', disasm_path, class: 'card-footer-item'
        .column.is-4
          .card
            header.card-header
              p.card-header-title
                | ZX Spectrum Emulator
            .card-content
              .content
                | JVGS v1.1.4 provides you with pure JavaScript client-side ZX Spectrum 48/128 emulation in current browser tab. Please expect this one-click solution to be a bit slow and requires some resources.
            footer.card-footer
              = link_to 'Emulator', emulator_path, class: 'card-footer-item'